import {Actor,State,Employee,Work,asISO} from './model';
export const allowed=(a:Actor,role:Actor['role'])=>{if(a.role!==role)throw Error(role==='admin'?'Administrator access required.':'Attendance is managed in the Foreman portal.');};
const id=()=>crypto.randomUUID();
function required(v:unknown,label:string){if(typeof v!=='string'||!v.trim())throw Error(label+' is required.');return v.trim();}
export function validatePerson(s:State,r:any,kind:'employee'|'foreman'){const name=required(r.name,'Name'),mobile=required(r.mobile,'Mobile number'),qid=required(r.qid,'QID number');if(!/^\d{11}$/.test(qid))throw Error('QID must be exactly 11 digits.');const list=kind==='employee'?s.employees:s.foremen;if(list.some(p=>p.id!==r.id&&p.qid===qid))throw Error('QID already exists');if(!['Active','Inactive'].includes(r.status))throw Error('Choose Active or Inactive status.');return {name,mobile,qid,status:r.status};}
export function projectUnlocked(s:State,work:Work,a:Actor){if(work.kind==='project'&&s.sessions.some(x=>x.work===work.id&&!x.checkout&&x.foreman!==a.id))throw Error('This Project is in use by another foreman. Wait until all their employees are checked out.');}
export function mutate(s:State,a:Actor,action:string,r:any){
 if(action==='save_employee'){allowed(a,'admin');const p=validatePerson(s,r,'employee');const existing=r.id?s.employees.find(e=>e.id===r.id):null;if(r.id&&!existing)throw Error('Employee not found.');if(existing)Object.assign(existing,p);else s.employees.push({...p,id:id(),code:'NJC-'+String(++s.counters.employee).padStart(3,'0')} as Employee);return;}
 if(action==='save_work'){allowed(a,'admin');const existing=r.id?s.work.find(w=>w.id===r.id):null;if(r.id&&!existing)throw Error('Work record not found.');if(!['project','maintenance'].includes(r.kind)||existing&&existing.kind!==r.kind)throw Error('Invalid work category.');if(!['Active','Inactive','Completed'].includes(r.status))throw Error('Invalid status.');const work:Work={id:existing?.id||id(),kind:r.kind,name:required(r.name,r.kind==='project'?'Project name':'Maintenance title'),location:required(r.location,'Location'),status:r.status};if(r.kind==='project'){work.startDate=required(r.startDate,'Start date');asISO(work.startDate+'T00:00');}else {work.propertyName=required(r.propertyName,'Property / villa name');if(existing?.startDate)work.startDate=existing.startDate;}if(r.status==='Completed')work.completionDate=existing?.completionDate||new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Qatar'}).format(new Date());else if(existing?.completionDate)work.completionDate=existing.completionDate;if(existing)Object.assign(existing,work);else s.work.push(work);return;}
 if(action==='selection'){allowed(a,'foreman');const work=s.work.find(w=>w.id===r.work);if(!work)throw Error('Work record not found.');if(!Array.isArray(r.employees))throw Error('Choose employees.');const selection=s.selections.find(x=>x.work===r.work&&x.foreman===a.id);const previous=new Set(selection?.employees||[]);const requested=[...new Set(r.employees)] as string[];for(const eid of previous){if(!requested.includes(eid)&&s.sessions.some(x=>x.employee===eid&&x.work===r.work&&x.foreman===a.id&&!x.checkout))throw Error('Check out the employee before unselecting them.');}for(const eid of requested){const e=s.employees.find(e=>e.id===eid);if(!e)throw Error('Employee not found.');if(!previous.has(eid)){if(work.status!=='Active')throw Error('Only active work accepts new employees.');projectUnlocked(s,work,a);if(e.status!=='Active')throw Error('Only active employees can be added.');const active=s.sessions.find(x=>x.employee===eid&&!x.checkout);if(active&&(active.work!==r.work||active.foreman!==a.id))throw Error(e.name+' has an active check-in. Complete checkout before selecting them.');}}if(selection)selection.employees=requested;else if(requested.length)s.selections.push({id:id(),foreman:a.id,work:r.work,employees:requested});return;}
 if(action==='checkin'||action==='checkout'){allowed(a,'foreman');if(!Array.isArray(r.employees)||!r.employees.length)throw Error('Select at least one employee.');const work=s.work.find(w=>w.id===r.work);if(!work||action==='checkin'&&work.status!=='Active')throw Error('This work is unavailable for new check-ins.');if(action==='checkin')projectUnlocked(s,work,a);const timestamp=r.datetime?asISO(r.datetime):new Date().toISOString();const time=Date.parse(timestamp);const selection=s.selections.find(x=>x.work===r.work&&x.foreman===a.id);const updates:{employee:string;session?:any}[]=[];for(const eid of [...new Set(r.employees)] as string[]){const e=s.employees.find(e=>e.id===eid);if(!e)throw Error('Employee not found.');if(action==='checkin'){if(e.status!=='Active')throw Error(e.name+' is inactive.');if(!selection?.employees.includes(eid))throw Error('Select employees for this work first.');if(s.sessions.some(x=>x.employee===eid&&!x.checkout))throw Error(e.name+' is already checked in.');if(s.sessions.some(x=>x.employee===eid&&x.checkout&&Date.parse(x.checkout)>time))throw Error(e.name+': check-in overlaps a recorded session.');updates.push({employee:eid});}else{const session=s.sessions.find(x=>x.employee===eid&&!x.checkout);if(!session)throw Error(e.name+' does not have an active check-in.');if(session.foreman!==a.id||session.work!==r.work)throw Error('You can only check out your own records for this work.');if(time<=Date.parse(session.checkin))throw Error(e.name+': checkout must be after check-in.');if(s.sessions.some(x=>x.id!==session.id&&x.employee===eid&&Date.parse(x.checkin)<time&&(!x.checkout||Date.parse(x.checkout)>Date.parse(session.checkin))))throw Error(e.name+': this time overlaps another work session.');updates.push({employee:eid,session});}}
 if(action==='checkin'&&work.kind==='maintenance'){const start=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Qatar'}).format(new Date(timestamp));if(!work.startDate||start<work.startDate)work.startDate=start;}
 for(const u of updates){if(action==='checkin')s.sessions.push({id:id(),employee:u.employee,work:r.work,foreman:a.id,checkin:timestamp,checkout:null});else u.session.checkout=timestamp;}return;
 }throw Error('Unknown action.');
}
