import {state,db,save,secret,actor,cookie,origin,error,json} from '../../server';
import {credentials,verify,seal,random,digest} from '../../security';
import {setupOwner} from '../../setup-owner';
import {State} from '../../model';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{const s=await state();if(!s)return json({setup:true});try{const a=await actor(req,s.data);return json({role:a.role,setup:false});}catch{return json({setup:false,role:null});}}catch(e){return error(e);}}
export async function POST(req:Request){try{origin(req);const {action,...r}=await req.json() as any;let s=await state();if(action==='signup'||action==='setup'){if(s)throw Error('The administrator account is already configured.');const email=String(r.email||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Enter a valid administrator email.');if(r.password!==r.confirm)throw Error('Passwords do not match.');const c=await credentials(r.password);const data:State={admin:{id:crypto.randomUUID(),name:'Administrator',email,credentials:c},company:{name:'NAJCO'},employees:[],foremen:[],work:[],selections:[],sessions:[],counters:{employee:0,foreman:0}};const res=await db().prepare('INSERT OR IGNORE INTO workforce360 (id,owner,body,revision) VALUES (1,?,?,0)').bind(email,JSON.stringify(data)).run();if(!res.meta.changes)throw Error('Setup has already completed. Please sign in.');return json({ok:true,message:'Account created. Please log in with your email and password.'});}
 if(!s)throw Error('Complete administrator setup first.');
 if(action==='logout')return json({ok:true},{'Set-Cookie':'wf360=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'});
 if(action==='login'){const username=String(r.username||'').trim().toLowerCase();const k=await digest(username);const window=Math.floor(Date.now()/900000);const attempt=await db().prepare('INSERT INTO workforce360_attempts (key,window,count) VALUES (?,?,1) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN window=excluded.window THEN count+1 ELSE 1 END,window=excluded.window RETURNING count').bind(k,window).first();if(attempt.count>15)throw Error('Too many sign-in attempts. Try again in 15 minutes.');const isAdmin=username===s.data.admin.email.toLowerCase();if(r.portal&&r.portal!==(isAdmin?'admin':'foreman'))throw Error('Use the correct portal for this account.');const user=isAdmin?s.data.admin:s.data.foremen.find(f=>f.code.toLowerCase()===username&&f.status==='Active');if(!user?.credentials||!await verify(r.password,user.credentials))throw Error('Incorrect username or password, or account inactive.');await db().prepare('DELETE FROM workforce360_attempts WHERE key=?').bind(k).run();return json({role:isAdmin?'admin':'foreman'},{'Set-Cookie':await cookie({id:user.id,role:isAdmin?'admin':'foreman',version:user.credentials.version})});}
 if(action==='forgot'){const email=String(r.email||'').trim().toLowerCase();const message='If the email matches the administrator profile, a recovery message has been prepared.';if(email!==s.data.admin.email.toLowerCase())return json({message});const platform=await setupOwner(r.setupKey,r.email);if(platform?.email.toLowerCase()!==s.owner)return json({message});const token=random();s.data.recovery={hash:await digest(token),expires:Date.now()+15*60000,used:false};await save(s.data,s.revision);return json({message,dummyMail:{to:email,subject:'Workforce360 — Reset your administrator password',link:'/reset?token='+token,notice:'Dummy inbox: this message is shown here for testing. No email was sent.'}});}
 if(action==='reset'){if(r.password!==r.confirm)throw Error('Passwords do not match.');const rec=s.data.recovery;if(!rec||rec.used||rec.expires<Date.now()||await digest(String(r.token||''))!==rec.hash)throw Error('This reset link is invalid or expired. Request a new one.');s.data.admin.credentials=await credentials(r.password,s.data.admin.credentials.version+1);rec.used=true;await save(s.data,s.revision);return json({ok:true});}
 throw Error('Unknown authentication action.');
 }catch(e){return error(e);}}
