export type Status='Active'|'Inactive';
export type Employee={id:string;code:string;name:string;qid:string;mobile:string;status:Status};
export type Credentials={salt:string;hash:string;version:number};
export type Foreman=Employee & {credentials?:Credentials;passwordCipher?:string;picture?:string};
export type Work={id:string;kind:'project'|'maintenance';name:string;location:string;propertyName?:string;startDate?:string;completionDate?:string;status:Status|'Completed'};
export type Session={id:string;employee:string;work:string;foreman:string;checkin:string;checkout:string|null};
export type Selection={id:string;foreman:string;work:string;employees:string[]};
export type Admin={id:string;name:string;email:string;picture?:string;credentials:Credentials};
export type State={admin:Admin;company:{name:string;logo?:string};employees:Employee[];foremen:Foreman[];work:Work[];selections:Selection[];sessions:Session[];counters:{employee:number;foreman:number};recovery?:{hash:string;expires:number;used:boolean}};
export type Actor={id:string;role:'admin'|'foreman';version:number};
export type ViewData={company:State['company'];employees:Employee[];foremen:(Omit<Foreman,'credentials'|'passwordCipher'>&{hasLogin:boolean})[];work:Work[];selections:Selection[];sessions:Session[];busy:string[];lockedProjects:string[];profile:{id:string;name:string;email?:string;code?:string;qid?:string;mobile?:string;picture?:string};role:Actor['role'];revision:number};
export function localDateTime(now=new Date()){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Qatar',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(now).replace(' ','T');}
export const today=()=>localDateTime().slice(0,10);
export function asISO(value:string){if(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value))throw Error('Enter a valid date and time.');const d=new Date(value+':00+03:00');if(!Number.isFinite(d.getTime())||localDateTime(d)!==value)throw Error('Enter a valid date and time.');return d.toISOString();}
export const hours=(s:Session)=>s.checkout?(Date.parse(s.checkout)-Date.parse(s.checkin))/3600000:0;
export function publicData(s:State,a:Actor,revision:number):ViewData{const sessions=a.role==='admin'?s.sessions:s.sessions.filter(x=>x.foreman===a.id);const history=new Set([...sessions.map(x=>x.employee),...s.selections.filter(x=>x.foreman===a.id).flatMap(x=>x.employees)]);const me=s.foremen.find(f=>f.id===a.id);return {company:s.company,employees:s.employees.filter(e=>a.role==='admin'||e.status==='Active'||history.has(e.id)),foremen:(a.role==='admin'?s.foremen:s.foremen.filter(f=>f.id===a.id)).map(({credentials,passwordCipher,...f})=>({...f,hasLogin:!!credentials})),work:s.work,selections:s.selections.filter(x=>a.role==='admin'||x.foreman===a.id),sessions,busy:[...new Set(s.sessions.filter(x=>!x.checkout).map(x=>x.employee))],lockedProjects:[...new Set(s.sessions.filter(x=>!x.checkout&&x.foreman!==a.id&&s.work.some(w=>w.id===x.work&&w.kind==='project')).map(x=>x.work))],profile:a.role==='admin'?{id:s.admin.id,name:s.admin.name,email:s.admin.email,picture:s.admin.picture}:{id:me!.id,name:me!.name,code:me!.code,qid:me!.qid,mobile:me!.mobile,picture:me!.picture},role:a.role,revision};}
export type ReportRow={employee:string;period:string;work:string;hours:number;checkin?:string;checkout?:string;foreman?:string};
export function reportRows(sessions:Session[],from:string,to:string,period:'daily'|'weekly'|'monthly'|'maximum',details=false):ReportRow[]{const result:ReportRow[]=[];if(period==='maximum'){const groups=new Map<string,ReportRow>();for(const s of sessions){if(!s.checkout)continue;const key=s.employee+'|'+s.work;const row=groups.get(key);if(row)row.hours+=hours(s);else groups.set(key,{employee:s.employee,work:s.work,period:'All time',hours:hours(s)});}return [...groups.values()];}const start=Date.parse(from+'T00:00:00+03:00'),end=Date.parse(to+'T00:00:00+03:00')+86400000;for(const s of sessions){if(!s.checkout)continue;const left=Math.max(start,Date.parse(s.checkin)),right=Math.min(end,Date.parse(s.checkout));for(let t=left;t<right;){const day=localDateTime(new Date(t)).slice(0,10);const midnight=Date.parse(day+'T00:00:00+03:00')+86400000;const next=Math.min(right,midnight);let key=day;if(period==='monthly')key=day.slice(0,7);if(period==='weekly'){const d=new Date(day+'T12:00:00Z');d.setUTCDate(d.getUTCDate()-(d.getUTCDay()+6)%7);key='Week of '+d.toISOString().slice(0,10);}result.push({employee:s.employee,work:s.work,period:key,hours:(next-t)/3600000,...(details?{checkin:s.checkin,checkout:s.checkout,foreman:s.foreman}:{})});t=next;}}if(details)return result;const groups=new Map<string,ReportRow>();for(const r of result){const key=[r.employee,r.work,r.period].join('|');const prev=groups.get(key);if(prev)prev.hours+=r.hours;else groups.set(key,{...r});}return [...groups.values()].sort((a,b)=>a.period.localeCompare(b.period)||a.employee.localeCompare(b.employee));}
